# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03a9c8105926703a3e778d468f71cc0ea3612879e894aa0d80c3a108fbd634c30d16f88340b23db459a7cef076aaaa116ccb7374696e4e8e2791e6ca6d9148ee

test:
  secret_key_base: 56fbf7ee4d674385aa6ed90c971ef05d7a65caf1843f2f336c4a4f8d2635d09ecd2cdda52b5334c14055d43365ec6463fa438b2904c2ef199068d41de1b54c4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
